name: flutter_mqtt_location_tracker
description: "A flutter app to track device locations."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  android_alarm_manager_plus: ^3.0.4
  app_settings: ^5.1.1
  audioplayers: ^5.2.1
  # background_fetch: ^1.2.1
  # background_locator_2: ^2.0.6
  # background_locator_2:
  #   git:
  #     url: https://github.com/ndesamuelmbah/background_locator_fixed.git
  #     ref: d24b73a02fae12570ba2ccfb377ce4e6c91f8b1c
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  country_code_picker:
    git:
      url: https://github.com/ndesamuelmbah/CountryCodePicker.git
      ref: a76eebfabfc3b5c041e63a0a724bd5553c7a778d

  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  encrypt: ^5.0.3
  file_picker: ^6.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_dynamic_links: ^5.4.8
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  # flutter_background_geolocation: ^4.13.5
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_local_notifications: ^16.2.0
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.0
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.1.2
  image_picker: ^1.0.5
  intl: ^0.19.0
  location: ^5.0.3
  logger: ^2.0.2+1
  logging: ^1.2.0
  mime: ^1.0.4
  # mqtt_client: ^10.0.0
  mqtt5_client: ^4.0.3
  path_provider: ^2.1.1
  package_info_plus: ^5.0.1
  permission_handler: ^11.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  signature: ^5.4.1
  universal_html: ^2.2.4
  url_launcher: ^6.2.2
  video_player: ^2.8.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    background_color: "#e7d5f2"
    theme_color: "#e7d5f2"
  windows:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    background_color: "#e7d5f2"
    theme_color: "#e7d5f2"
    image_path: "assets/images/launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/launcher_icon.png
    - assets/images/splash.png
    - assets/sounds/papaandmama.mp3
    - assets/sounds/wilsamsonnde.mp3
    - assets/sounds/lansonnde.mp3
    - assets/sounds/papaandshiphrah.mp3
    - assets/sounds/papaonly.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
