// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxVKEwpOw8Uf1VJm42AbBAmof2-M_8IK0',
    appId: '1:362591334361:web:27d41aecc1045684c873c8',
    messagingSenderId: '362591334361',
    projectId: 'samuels-device-tracker',
    authDomain: 'samuels-device-tracker.firebaseapp.com',
    storageBucket: 'samuels-device-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHfnMeoMembolk0GGyDfkLce2XRMshdg',
    appId: '1:362591334361:android:6d0f4110942e9ffbc873c8',
    messagingSenderId: '362591334361',
    projectId: 'samuels-device-tracker',
    storageBucket: 'samuels-device-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEToMCpukNpG8raDh-yAU6dFq8QyEa_m0',
    appId: '1:362591334361:ios:c71758027b3ba407c873c8',
    messagingSenderId: '362591334361',
    projectId: 'samuels-device-tracker',
    storageBucket: 'samuels-device-tracker.appspot.com',
    iosBundleId: 'com.samuelnde.flutterMqttLocationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEToMCpukNpG8raDh-yAU6dFq8QyEa_m0',
    appId: '1:362591334361:ios:0a6d33e222c02e62c873c8',
    messagingSenderId: '362591334361',
    projectId: 'samuels-device-tracker',
    storageBucket: 'samuels-device-tracker.appspot.com',
    iosBundleId: 'com.samuelnde.flutterMqttLocationTracker.RunnerTests',
  );
}
